# Generated by Django 5.0 on 2025-02-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('telp', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masyarakat',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('telp', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'masyarakat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_petugas', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('telp', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'petugas',
            },
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id_pengaduan', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_pengaduan', models.DateField(auto_now_add=True)),
                ('isi_laporan', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengaduan_foto/')),
                ('kategori', models.CharField(choices=[('infrastruktur', 'Infrastruktur'), ('lingkungan', 'Lingkungan'), ('kriminal', 'Kriminal'), ('pelayanan', 'Pelayanan Publik'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('lokasi', models.CharField(default='Tidak diketahui', max_length=255)),
                ('status', models.CharField(choices=[('tunggu', 'Belum diproses'), ('proses', 'Sedang diproses'), ('selesai', 'Selesai')], default='tunggu', max_length=10)),
                ('nik', models.ForeignKey(db_column='nik', on_delete=django.db.models.deletion.CASCADE, to='laporan.masyarakat')),
            ],
            options={
                'db_table': 'pengaduan',
            },
        ),
        migrations.CreateModel(
            name='Tanggapan',
            fields=[
                ('id_tanggapan', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_tanggapan', models.DateTimeField(auto_now_add=True)),
                ('tanggapan', models.TextField()),
                ('id_admin', models.ForeignKey(blank=True, db_column='id_admin', null=True, on_delete=django.db.models.deletion.CASCADE, to='laporan.administrator')),
                ('id_pengaduan', models.ForeignKey(db_column='id_pengaduan', on_delete=django.db.models.deletion.CASCADE, to='laporan.pengaduan')),
                ('id_petugas', models.ForeignKey(blank=True, db_column='id_petugas', null=True, on_delete=django.db.models.deletion.CASCADE, to='laporan.petugas')),
            ],
            options={
                'db_table': 'tanggapan',
            },
        ),
    ]
