# Generated by Django 5.1.5 on 2025-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('telp', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masyarakat',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('telp', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'masyarakat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id_pengaduan', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_pengaduan', models.DateField(auto_now_add=True)),
                ('isi_laporan', models.TextField()),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('tunggu', 'Belum diproses'), ('proses', 'Sedang diproses'), ('selesai', 'Selesai')], default='tunggu', max_length=10)),
            ],
            options={
                'db_table': 'pengaduan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_petugas', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('telp', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'petugas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tanggapan',
            fields=[
                ('id_tanggapan', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_tanggapan', models.DateField(auto_now_add=True)),
                ('tanggapan', models.TextField()),
            ],
            options={
                'db_table': 'tanggapan',
                'managed': False,
            },
        ),
    ]
