# Generated by Django 5.1.5 on 2025-02-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengaduan',
            options={},
        ),
    ]
