# Generated by Django 5.0 on 2025-02-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petugas',
            name='role',
            field=models.CharField(default='petugas', max_length=20),
        ),
    ]
