# Generated by Django 5.0 on 2025-02-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_petugas_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={},
        ),
    ]
