# Generated by Django 5.1.5 on 2025-02-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_alter_administrator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pengaduan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='petugas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tanggapan',
            options={'managed': False},
        ),
    ]
