# Generated by Django 5.1.5 on 2025-02-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0004_alter_administrator_options_alter_pengaduan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengaduan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='petugas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tanggapan',
            options={},
        ),
    ]
