# Generated by Django 5.1.5 on 2025-02-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_alter_pengaduan_options_alter_petugas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='kategori_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petugas',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='tgl_pengaduan',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='role',
            field=models.CharField(default='petugas', max_length=50),
        ),
    ]
