# Generated by Django 5.0 on 2025-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0005_alter_pengaduan_options_alter_petugas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petugas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petugas_foto/'),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='role',
            field=models.CharField(default='petugas', max_length=50),
        ),
    ]
