# Generated by Django 5.1.5 on 2025-02-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0006_pengaduan_kategori_lainnya_petugas_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petugas',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profil/'),
        ),
    ]
